# Get data for the parent dashboard
query GetParentDashboardData($parentId: String!) {
  usersCollection(filter: { userId: { eq: $parentId }, role: { eq: PARENT } }) {
    edges {
      node {
        userId
        firstName
        lastName
        parentLinksAsParent(
          # Removed filter: {} as it's not needed if we want all linked students
        ) {
          edges {
            node {
              relationshipType
              student { # This is the User object for the student
                userId
                firstName
                lastName
                studentProfile {
                  currentGradeLevel
                  # You might want to fetch profile picture URL here if stored
                }
                gradesAsStudent(orderBy: [{recordedAt: DescNullsLast}], limit: 5) { # Fetch recent 5 grades
                  edges {
                    node {
                      gradeId
                      term
                      score
                      comments
                      subject {
                        subjectName
                      }
                      class {
                        className
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}